#ifndef SIXTRACKLIB_COMMON_IMPL_BUFFER_OBJECT_UNDEF_H__
#define SIXTRACKLIB_COMMON_IMPL_BUFFER_OBJECT_UNDEF_H__

#if defined( SIXTRL_BUFFER_OBJ_ARGPTR_DEC_UNDEF )
    #undef SIXTRL_BUFFER_OBJ_ARGPTR_DEC_UNDEF
    #undef SIXTRL_BUFFER_OBJ_ARGPTR_DEC
#endif /* defined( SIXTRL_BUFFER_OBJ_ARGPTR_DEC_UNDEF ) */

#if defined( SIXTRL_BUFFER_OBJ_DATAPTR_DEC_UNDEF )
    #undef SIXTRL_BUFFER_OBJ_DATAPTR_DEC_UNDEF
    #undef SIXTRL_BUFFER_OBJ_DATAPTR_DEC
#endif /* defined( SIXTRL_BUFFER_OBJ_DATAPTR_DEC_UNDEF ) */

#endif /* SIXTRACKLIB_COMMON_IMPL_BUFFER_OBJECT_UNDEF_H__ */
/* end: sixtracklib/common/impl/buffer_object_defines.h */
