#ifndef SIXTRACKLIB_COMMON_IMPL_BUFFER_GARBAGE_RANGE_DEFINES_H__
#define SIXTRACKLIB_COMMON_IMPL_BUFFER_GARBAGE_RANGE_DEFINES_H__

#if !defined( SIXTRL_BUFFER_GARBAGE_ARGPTR_DEC )
    #define SIXTRL_BUFFER_GARBAGE_ARGPTR_DEC_UNDEF
    #if defined( SIXTRL_BUFFER_DATAPTR_DEC )
        #define  SIXTRL_BUFFER_GARBAGE_ARGPTR_DEC SIXTRL_BUFFER_DATAPTR_DEC
    #elif defined( SIXTRL_ARGPTR_DEC )
        #define  SIXTRL_BUFFER_GARBAGE_ARGPTR_DEC SIXTRL_DATAPTR_DEC
    #else /* !defined( SIXTRL_ARGPTR_DEC ) */
        #define SIXTRL_BUFFER_GARBAGE_ARGPTR_DEC
    #endif /* defined( SIXTRL_ARGPTR_DEC ) */
#endif /* !defined( SIXTRL_BUFFER_GARBAGE_ARGPTR_DEC ) */

#if !defined( SIXTRL_BUFFER_GARBAGE_DATAPTR_DEC )
    #define SIXTRL_BUFFER_GARBAGE_DATAPTR_DEC_UNDEF
    #if defined( SIXTRL_BUFFER_DATAPTR_DEC )
        #define  SIXTRL_BUFFER_GARBAGE_DATAPTR_DEC SIXTRL_BUFFER_DATAPTR_DEC
    #elif defined( SIXTRL_DATAPTR_DEC )
        #define  SIXTRL_BUFFER_GARBAGE_DATAPTR_DEC SIXTRL_DATAPTR_DEC
    #else /* !defined( SIXTRL_DATAPTR_DEC ) */
        #define SIXTRL_BUFFER_GARBAGE_DATAPTR_DEC
    #endif /* defined( SIXTRL_DATAPTR_DEC ) */
#endif /* !defined( SIXTRL_BUFFER_GARBAGE_DATAPTR_DEC ) */

#endif /* SIXTRACKLIB_COMMON_IMPL_BUFFER_GARBAGE_RANGE_DEFINES_H__ */

/* end: sixtracklib/common/impl/buffer_garbage_defines.h */
