#ifndef SIXTRACKLIB_COMMON_IMPL_PARTICLES_DEFINES_H__
#define SIXTRACKLIB_COMMON_IMPL_PARTICLES_DEFINES_H__

#if !defined( SIXTRL_PARTICLE_ARGPTR_DEC )
    #define   SIXTRL_PARTICLE_ARGPTR_DEC_UNDEF
    #if defined( SIXTRL_BUFFER_DATAPTR_DEC )
        #define  SIXTRL_PARTICLE_ARGPTR_DEC SIXTRL_BUFFER_DATAPTR_DEC
    #elif defined( SIXTRL_DATAPTR_DEC )
        #define  SIXTRL_PARTICLE_ARGPTR_DEC SIXTRL_DATAPTR_DEC
    #else
        #define  SIXTRL_PARTICLE_ARGPTR_DEC
    #endif
#endif /* SIXTRL_PARTICLE_ARGPTR_DEC */

#if !defined( SIXTRL_PARTICLE_DATAPTR_DEC )
    #define   SIXTRL_PARTICLE_DATAPTR_DEC_UNDEF
    #if defined( SIXTRL_PARTICLE_DATAPTR_DEC )
        #define  SIXTRL_PARTICLE_DATAPTR_DEC SIXTRL_BUFFER_DATAPTR_DEC
    #elif defined( SIXTRL_DATAPTR_DEC )
        #define  SIXTRL_PARTICLE_DATAPTR_DEC SIXTRL_DATAPTR_DEC
    #else
        #define  SIXTRL_PARTICLE_DATAPTR_DEC
    #endif
#endif /* SIXTRL_PARTICLE_DATAPTR_DEC */

#endif /* SIXTRACKLIB_COMMON_IMPL_PARTICLES_DEFINES_H__ */

/* end: sixtracklib/common/impl/particles_defines.h */
