#ifndef SIXTRACKLIB_COMMON_INTERNAL_BUFFER_MAIN_UNDEF_H__
#define SIXTRACKLIB_COMMON_INTERNAL_BUFFER_MAIN_UNDEF_H__

#if defined( SIXTRL_BUFFER_ARGPTR_DEC_UNDEF )
    #undef   SIXTRL_BUFFER_ARGPTR_DEC_UNDEF
    #undef   SIXTRL_BUFFER_ARGPTR_DEC
#endif /* !defined( SIXTRL_BUFFER_ARGPTR_DEC_UNDEF ) */

#if defined( SIXTRL_BUFFER_DATAPTR_DEC_UNDEF )
    #undef   SIXTRL_BUFFER_DATAPTR_DEC_UNDEF
    #undef   SIXTRL_BUFFER_DATAPTR_DEC
#endif /* !defined( SIXTRL_BUFFER_DATAPTR_DEC_UNDEF ) */

#endif /* SIXTRACKLIB_COMMON_INTERNAL_BUFFER_MAIN_UNDEF_H__ */

/* end: sixtracklib/common/internal/buffer_main_undef.h */
