#ifndef SIXTRACKLIB_COMMON_INTERNAL_ELEM_BY_ELEM_CONFIG_UNDEF_H__
#define SIXTRACKLIB_COMMON_INTERNAL_ELEM_BY_ELEM_CONFIG_UNDEF_H__

#if defined( SIXTRL_ELEM_BY_ELEM_CONFIG_ARGPTR_DEC_UNDEF )
    #undef SIXTRL_ELEM_BY_ELEM_CONFIG_ARGPTR_DEC_UNDEF
    #undef SIXTRL_ELEM_BY_ELEM_CONFIG_ARGPTR_DEC
#endif /* defined( SIXTRL_ELEM_BY_ELEM_CONFIG_ARGPTR_DEC_UNDEF ) */

#endif /* SIXTRACKLIB_COMMON_INTERNAL_ELEM_BY_ELEM_CONFIG_UNDEF_H__ */

/* end: sixtracklib/common/internal/elem_by_elem_config_undef.h */
