#ifndef SIXTRACKLIB_COMMON_INTERNAL_ELEM_BY_ELEM_CONFIG_DEFINES_H__
#define SIXTRACKLIB_COMMON_INTERNAL_ELEM_BY_ELEM_CONFIG_DEFINES_H__

#if !defined( SIXTRL_ELEM_BY_ELEM_CONFIG_ARGPTR_DEC )
    #define   SIXTRL_ELEM_BY_ELEM_CONFIG_ARGPTR_DEC_UNDEF
    #if defined( SIXTRL_BUFFER_DATAPTR_DEC )
        #define  SIXTRL_ELEM_BY_ELEM_CONFIG_ARGPTR_DEC SIXTRL_BUFFER_DATAPTR_DEC
    #elif defined( SIXTRL_DATAPTR_DEC )
        #define  SIXTRL_ELEM_BY_ELEM_CONFIG_ARGPTR_DEC SIXTRL_DATAPTR_DEC
    #else
        #define  SIXTRL_ELEM_BY_ELEM_CONFIG_ARGPTR_DEC
    #endif
#endif /* SIXTRL_ELEM_BY_ELEM_CONFIG_ARGPTR_DEC */

#endif /* SIXTRACKLIB_COMMON_INTERNAL_ELEM_BY_ELEM_CONFIG_DEFINES_H__ */

/* end: sixtracklib/common/internal/elem_by_elem_config_defines.h */
