#ifndef SIXTRACKLIB_COMMON_INTERNAL_PARTICLES_UNDEF_H__
#define SIXTRACKLIB_COMMON_INTERNAL_PARTICLES_UNDEF_H__

#if defined( SIXTRL_PARTICLE_ARGPTR_DEC_UNDEF )
    #undef SIXTRL_PARTICLE_ARGPTR_DEC_UNDEF
    #undef SIXTRL_PARTICLE_ARGPTR_DEC
#endif /* defined( SIXTRL_PARTICLE_ARGPTR_DEC_UNDEF ) */

#if defined( SIXTRL_PARTICLE_DATAPTR_DEC_UNDEF )
    #undef SIXTRL_PARTICLE_DATAPTR_DEC_UNDEF
    #undef SIXTRL_PARTICLE_DATAPTR_DEC
#endif /* defined( SIXTRL_PARTICLE_DATAPTR_DEC_UNDEF ) */

#endif /* SIXTRACKLIB_COMMON_INTERNAL_PARTICLES_UNDEF_H__ */

/* end: sixtracklib/common/internal/particles_undef.h */
